# Generated by Django 5.0.9 on 2024-11-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('id_number', models.CharField(max_length=12)),
                ('license_plate', models.CharField(max_length=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('activate', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timeline', models.DateTimeField(auto_now_add=True)),
                ('gate', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='prove.person')),
            ],
        ),
    ]
