# Generated by Django 5.0.9 on 2024-11-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prove', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='license_plate',
            field=models.CharField(max_length=15),
        ),
    ]
